use [SistemaHospitales]
 
-- 11. ROLES
CREATE TABLE ROLES (
    IDRol INT PRIMARY KEY IDENTITY(1,1),
    NombreRol VARCHAR(50) UNIQUE NOT NULL,
    Descripcion VARCHAR(200),
    FechaRegistro DATETIME DEFAULT GETDATE()
);
 
-- 12. PERMISOS
CREATE TABLE PERMISOS (
    IDPermiso INT PRIMARY KEY IDENTITY(1,1),
    NombrePermiso VARCHAR(100) UNIQUE NOT NULL,
    Descripcion VARCHAR(200),
    Modulo VARCHAR(50),
    FechaRegistro DATETIME DEFAULT GETDATE()
);
 
-- 13. ROLES_PERMISOS (Tabla Puente)
CREATE TABLE ROLES_PERMISOS (
    IDRolPermiso INT PRIMARY KEY IDENTITY(1,1),
    IDRol INT NOT NULL,
    IDPermiso INT NOT NULL,
    FOREIGN KEY (IDRol) REFERENCES ROLES(IDRol),
    FOREIGN KEY (IDPermiso) REFERENCES PERMISOS(IDPermiso),
    UNIQUE(IDRol, IDPermiso)
);
 
-- 14. USUARIOS
CREATE TABLE USUARIOS (
    IDUsuario INT PRIMARY KEY IDENTITY(1,1),
    IDRol INT NOT NULL,
    IDHospital INT,
    IDPaciente INT,
    IDMedico INT,
    Username VARCHAR(50) UNIQUE NOT NULL,
    PasswordHash VARCHAR(255) NOT NULL,
    Email VARCHAR(100),
    FechaCreacion DATETIME DEFAULT GETDATE(),
    FechaUltimoLogin DATETIME,
    Estado CHAR(1) DEFAULT 'A' CHECK (Estado IN ('A', 'I')),
    FOREIGN KEY (IDRol) REFERENCES ROLES(IDRol),
    FOREIGN KEY (IDHospital) REFERENCES HOSPITALES(IDHospital),
    FOREIGN KEY (IDPaciente) REFERENCES PACIENTES(IDPaciente),
    FOREIGN KEY (IDMedico) REFERENCES MEDICOS(IDMedico)
);